# Generated by Django 2.0.5 on 2018-09-12 23:48

from django.db import migrations

def seed(apps, schema_editor):
    Post = apps.get_model('scribble', 'Post')
    Comment = apps.get_model('scribble', 'Comment')

    petunias = Post(author="Douglas Adams", title="Deadlines", body="Yet another wooshes by.")
    dunes = Post(author="Frank Herbert", title="Dunes", body="The spice must flow.")
    robots = Post(author="Isaac Asimov", title="iBots", body="Apple two words for ya: copyright infringement.")
    dystopias = Post(author="George Orwell", title="The eighties", body="Wait til we get to 2016.")
    petunias.save()
    dunes.save()
    robots.save()
    dystopias.save()

    Comment(author = 'JR Tolkein', post=petunias, body='I did not finish my novel either bro').save()
    Comment(author = '100% Human', post=robots, body='I too am disturbed, human friend.').save()
    Comment(author = 'Baron', post=dunes, body='Stop putting words in my mouth').save()
    Comment(author = 'Tank Girl' , post=dystopias, body='Just wait til 2020!').save()
    Comment(author = 'Mad Max', post=dystopias, body='..........').save()
    Comment(author = 'Arthur', post=petunias, body='I guess there are worse things to complain about...').save()


def fallow(apps, schema_editor):
    Comment = apps.get_model('scribble', 'Comment')
    Post = apps.get_model('scribble', 'Post')
    Post.objects.all().delete()
    Comment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
